version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app

  backend1:
    container_name: backend1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app 
    environment:
      - PORT=3001
      - NAME=backend1