version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    user: 1000:1000
    environment:
      - TZ=America/Montreal
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:r

  backend1:
    container_name: backend1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app 
    environment:
      - PORT=3001
      - NAME=backend1