version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app:rw
    depends_on:
      - mosquitto
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    #user: 1000:1000
    environment:
      - TZ=America/Montreal
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend1:
    container_name: backend1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app:rw
    environment:
      - PORT=3001
      - NAME=backend1
    depends_on:
      - mosquitto

  backend2:
    container_name: backend2
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/app:rw
    environment:
      - PORT=3002
      - NAME=backend2
    depends_on:
      - mosquitto
      - backend1

  backend3:
    container_name: backend3
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/app:rw
    environment:
      - PORT=3003
      - NAME=backend3
    depends_on:
      - mosquitto
      - backend1
      - backend2

  backend4:
    container_name: backend4
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./backend:/app:rw
    environment:
      - PORT=3004
      - NAME=backend4
    depends_on:
      - mosquitto
      - backend1
      - backend2
      - backend3
    
  backend5:
    container_name: backend5
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./backend:/app:rw
    environment:
      - PORT=3005
      - NAME=backend5
    depends_on:
      - mosquitto
      - backend1
      - backend2
      - backend3
      - backend4