FROM node:16

ENV NODE_ENV=development
WORKDIR /app

COPY package.json ./

RUN npm install

RUN npm install -g nodemon

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that your Express app will listen on
#EXPOSE 3001

# Use nodemon to start your Express app (with automatic code reloading)
CMD ["nodemon", "index.js"]
